[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "universal-llm-safeguard"
version = "0.1.0"
description = "Universal middleware for safeguarding AI-generated content"
authors = [
  { name="Julius Deane", email="your@email.com" }
]
license = { file="LICENSE" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "fastapi",
  "flask",
  "django",
  "requests",
  "transformers"
]
